name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: install, lint, test
      run: |
        npm install -g yarn
        yarn install
        yarn lint:js
        yarn test

  try-scenarios:
    name: Ember Try Scenarios

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ember-try-scenario:
         - ember-lts-2.12
         - ember-lts-2.16
         - ember-lts-2.18
         - ember-3.1
         - ember-3.2
         - ember-3.3
         - ember-lts-3.4
         - ember-lts-3.8
         - ember-release
         - ember-beta
         - ember-canary
         - ember-default

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: test ${{ matrix.ember-try-scenario }}
      env:
        EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
      run: |
        npm install -g yarn
        yarn install
        node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
